language: node_js
node_js:
- '5'
- '0.8'
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: MTzpE800O1lHkQmLkKMYsdFdC/zCvxGTy72+0IuuzLYATCugdqDTubUVwjs5zFErD4tqBTsY3eE86X8wMyzz48cbBiQYksawxfuyTeKm80fwppQpjfkdfjBmv+MzGY/RL1hPv2ReF7hnglIZh4+CFJ68iNkRwntKfqaGz9aSQMPaJreHbed+lucQfKiGH9rTnuh1Nvl3jmb09Ubeh+QOVjJJUcoUPyEJaUo9HiB1MzrQ2ETSAL4fPwx4htU0e9GFd6DNseZCsDpeUhZ/mAo6t3rpzHyO+qem9J39qr0CTjAKVrwTGgxh/7Pd7JyekIJCooH06kAbUtOfUbDyBIFModGmoI01IlF4P5W4grJXnZPvEKpgPfrm2OdBY6Qe5boI2dabC5C1mcsV045CLYxVWjjAbbh7ppcNe3VzuVXyIXQcFL+2hTXkvysyfN+nR/aC9B6V6Bax9smnmnKjGEXiTVd5uJKLdrAu+bEQBHutzmSbbJhjQT2cZY/MV1fSBbaU22ARuKE93AIqdnkf1vrXtoUmyPCgslnmAUt2QFjuTpdVROw8H8TMx3TnATCnxCWe9wZ50pIVcYbOruWwYFxyBX95pPlewvPxZIegEkm7jYtSFoGZ38H0hMM/dAjs51wTUqr+w6Jlx/6c68B4SvwEl4spct3NYsOX0ndsaRAGVko=
  app: my-chess
  run: npm start
